# Generated by Django 2.2 on 2021-12-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211207_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.TextField(max_length=100),
        ),
    ]
